# Generated by Django 3.2.4 on 2021-09-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_author_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='post',
        ),
    ]
